# AJAY KUMAR (DATA MINING ASSIGNMENT 5)

In [99]:
import os
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import VarianceThreshold
import numpy as np
import timeit
from numpy import linalg as LA
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from sklearn import metrics 
from sklearn.metrics import classification_report, confusion_matrix,roc_curve,f1_score
import seaborn as sns
from scipy.stats import multivariate_normal
from sklearn.model_selection import KFold 
from scipy.spatial.distance import cdist
%matplotli

UsageError: Line magic function `%matplotli` not found.

# Question 1/program

In [100]:
df1 = pd.read_csv("C:\\Users\\hp\\assign_5\\data1.csv",header=None)

In [101]:
df1.insert(0,"x0",1)
df1.columns = [0,1,2,3]
df1.head()

   0        1        2        3
0  1  1.10500 -2.60510  34.2610
1  1  0.30463  1.55360   1.1477
2  1  2.67450  1.17810  15.6260
3  1 -3.54260  0.79471 -12.7760
4  1 -0.22632  4.44160 -21.7230

In [102]:
Dtrain,Dtest = train_test_split(df1,test_size=0.25,random_state=0)
Dtrain.head()

     0        1       2       3
71   1  0.51357 -2.4009  32.374
124  1 -4.25530  1.8827 -28.955
184  1  1.19990  4.0235 -19.164
97   1 -3.01370  4.7480 -35.305
149  1  4.56090 -4.4454  59.422

In [103]:
l = np.logspace(-2,0,20)
training_error = []
validation_error = []

from sklearn.model_selection import train_test_split 
Dtrain,Dtest = train_test_split(df1,test_size=0.25,random_state=0)
Dtrain.head()

I = np.zeros((Dtrain.shape[1]-1,Dtrain.shape[1]-1))
I[1:,1:] = np.eye(Dtrain.shape[1]-2)
for k in l:
    te = np.zeros(30)
    ve = np.zeros(30)
    for j in range(30):
    train,valid = train_test_split(Dtrain,test_size=0.25)
    # Training
    X = np.array(train[[0,1,2]])
    y = np.array(train[3])
    w = np.linalg.inv(X.T@X+k*I)@X.T@y
    # Training error
    te[j] = ((X@w-y)**2).mean()
    # Validation error
    X = np.array(valid[[0,1,2]])
    y = np.array(valid[3])
    ve[j]= ((X@w-y)**2).mean()
  training_error.append(te.mean())
  validation_error.append(ve.mean())
print(l)
print(training_error)
print(validation_error)

[0.01       0.01274275 0.01623777 0.02069138 0.02636651 0.03359818
 0.04281332 0.05455595 0.06951928 0.08858668 0.11288379 0.14384499
 0.18329807 0.23357215 0.29763514 0.37926902 0.48329302 0.61584821
 0.78475997 1.        ]
[15.695119195104063, 15.61164911312825, 15.693255062706816, 15.694944949288852, 15.747729432062615, 15.461558179338867, 15.848336822193, 15.64167658421933, 15.558013286993265, 15.747968515477885, 15.752716895576786, 15.807011543692239, 15.68412989118895, 15.520978456579616, 15.674033599225874, 15.759046528289502, 15.559616788167148, 15.719492335161153, 15.523406504945827, 15.599762348850627]
[16.555161605507198, 16.847955075223236, 16.52895836938191, 16.520659429118997, 16.43611924185358, 17.329365741086722, 16.013696866191466, 16.705844165233675, 16.99403328156705, 16.361753859501622, 16.369412745294728, 16.360370575266035, 16.56570724757906, 17.11626113722155, 16.67985518184473, 16.38825874568927, 17.015192953460637, 16.354744361006585, 17.167906505409697, 16.759439591458932]

In [104]:
#importing the data
df4 = pd.read_csv('C:\\Users\\hp\\assign_5\\data1.csv',header=None)
N,n = df4.shape[0], df4.shape[1]

# Assigning Labels to the data
names=[]
for i in range(1,n):
    names.append('x'+str(i))
names.append('Y')
df4.columns = names

# Adding the bias column
df4.insert(0, 'x0', 1)

# Creating the X and Y
X_full=df4[df4.columns[0:n]]
Y_full=df4[df4.columns[n]]

X, x_t, Y, y_t = train_test_split(X_full, Y_full, test_size = 0.3)

# Finding the parameters for the model
a=LA.inv(np.dot(X,X.T))
b=np.dot(a,Y)
W=np.dot(X.T,b)
print("\n The parameters for the model are\n",W)
          
# Computing the performance measure using mean-square error
y_tp=np.dot(x_t,W)
sqr_err=(y_tp-y_t)**2
mse=1/(len(y_t)) * np.sum(sqr_err)
print("\n The mean sqaure error for the model is \n", mse)

 The parameters for the model are
 [ -58.    8. -336.]

 The mean sqaure error for the model is
 998856.1882054567

In [54]:
df4.describe()

          x0          x1          x2           Y
count  200.0  200.000000  200.000000  200.000000
mean     1.0   -0.124053   -0.122621    8.238073
std      0.0    2.833827    2.847886   23.068654
min      1.0   -4.941700   -4.998100  -51.478000
25%      1.0   -2.582175   -2.380425   -9.113900
50%      1.0    0.141255   -0.234475    9.332900
75%      1.0    2.139825    1.927975   23.386500
max      1.0    4.917200    4.967100   62.702000

# Question 2/program

# Analyze Data 2 using regularized logistic regression

In [69]:
import os
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import VarianceThreshold
import numpy as np
import timeit
from numpy import linalg as LA
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from sklearn import metrics 
from sklearn.metrics import classification_report, confusion_matrix,roc_curve,f1_score
import seaborn as sns
from scipy.stats import multivariate_normal
from sklearn.model_selection import KFold 
from scipy.spatial.distance import cdist
%matplotlib

Using matplotlib backend: Qt5Agg

In [70]:
df2= pd.read_csv("C:\\Users\\hp\\assign_5\\data2.csv",header=None)

In [71]:
df2.insert(0,"x0",1)
df2.columns = range(0,5)
df2.head()

   0       1        2        3  4
0  1 -49.966 -11.5760 -13.5500  1
1  1 -49.676  37.6910  -6.3181 -1
2  1 -49.469 -23.7300 -41.7090 -1
3  1 -49.395  -3.4131   6.1457  1
4  1 -49.241  -9.9994  24.9850 -1

In [72]:
from sklearn.model_selection import train_test_split 
Dtrain,Dtest = train_test_split(df2,test_size=0.25,random_state=0)
Dtest.head()

     0        1       2         3  4
18   1 -44.0080 -22.834   0.19704 -1
170  1  34.2660  19.222  -8.34120 -1
107  1   6.0787 -47.923   5.42770 -1
98   1  -3.2340 -15.133 -24.84000 -1
177  1  37.1710  26.116 -24.98800 -1

In [73]:
from sklearn.preprocessing import StandardScaler 
scaler = StandardScaler()
Dtrain[[1,2,3]] = scaler.fit_transform(Dtrain[range(1,4)])
Dtrain.head()

<ipython-input-73-c3ac5e52d011>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Dtrain[[1,2,3]] = scaler.fit_transform(Dtrain[range(1,4)])
C:\Users\hp\anaconda3\lib\site-packages\pandas\core\indexing.py:1738: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value[:, i].tolist(), pi)

     0         1         2         3  4
71   1 -0.625776 -0.597588  1.386731  1
124  1  0.460253  1.082668 -0.787165 -1
184  1  1.397566 -0.145475  0.593914  1
97   1 -0.062679  1.442336 -0.271299 -1
149  1  0.977111  1.060220  0.727809 -1

In [74]:
df2[3] = 0.5*(df2[3]+1)

In [75]:
df2.insert(0,"x0",1)

In [76]:
Dtrain,Dtest = train_test_split(df2,test_size=0.25,random_state=0)

In [77]:
def sigmoid(X,w):
    return 1/(1+np.exp(-np.inner(w,X)))
def regularised_logistic(X,y,a,l,tol=1):
    plot_data = []
    w = 10*np.random.random(len(X[0]))
    I = np.zeros((len(w),len(w)))
    I[1:,1:] = np.eye(len(w)-1)
    Xtrain,Xvalid,Ytrain,Yvalid = train_test_split(X,y,test_size=0.2,random_state=0)
    J = 20
    while True:
        Jold = J
        for i in range(len(Xtrain)):
            f = sigmoid(Xtrain[i],w)
            w = w + a*(Ytrain[i]-f)*Xtrain[i] - l*(w@I)
        J = 0
        for j in range(len(Xvalid)):
            f = sigmoid(Xvalid[j],w)
            J += (-Yvalid[j]*np.log(f)-(1-Yvalid[j])*np.log(1-f) + 0.5*l*np.linalg.norm(w@I))
        plot_data.append(J)
        if J <= tol:
            break
        elif Jold == J:
            break
        print(J)
    return w,plot_data

In [78]:
# Cross validation
import math
alphas = np.logspace(-3,-0.5,5)
lambdas = np.logspace(-2,0,5)
data = [[],[],[]]
for a in alphas:
    for l in lambdas:
        Xtrain,Xvalid,Ytrain,Yvalid = train_test_split(Dtrain[range(0,4)],Dtrain[4],test_size=0.25)
        Xtrain = np.array(Xtrain)
        Xvalid = np.array(Xvalid)
        Ytrain = np.array(Ytrain)
        Yvalid = np.array(Yvalid)
        w = np.random.random(len(Xtrain[0]))
        I = np.zeros((len(w),len(w)))
        I[1:,1:] = np.eye(len(w)-1)
        for j in range(10):
            for i in range(len(Xtrain)):
                f = sigmoid(Xtrain[i],w)
                w = w + a*(Ytrain[i]-f)*Xtrain[i] - l*(w@I)
        J = 0
        for j in range(len(Xvalid)):
            f = sigmoid(Xvalid[j],w)
            if math.isnan(f):
                continue
            h1 = np.log(f)
            h2 = np.log(1-f)
            reg_term = 0.5*l*np.linalg.norm(w@I)
            add_term = (-Yvalid[j]*h1-(1-Yvalid[j])*h2 + reg_term)
            J += add_term
        data[0].append(a)
        data[1].append(l)
        data[2].append(J)
print(data)

ax = plt.figure().gca(projection="3d")
ax.scatter3D(data[0],data[1],data[2],depthshade=False)
plt.show()

<ipython-input-78-053ad115dac1>:26: RuntimeWarning: divide by zero encountered in log
  h2 = np.log(1-f)
<ipython-input-78-053ad115dac1>:28: RuntimeWarning: invalid value encountered in multiply
  add_term = (-Yvalid[j]*h1-(1-Yvalid[j])*h2 + reg_term)
<ipython-input-77-2926b799cc42>:2: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-np.inner(w,X)))
<ipython-input-78-053ad115dac1>:25: RuntimeWarning: divide by zero encountered in log
  h1 = np.log(f)
<ipython-input-78-053ad115dac1>:29: RuntimeWarning: invalid value encountered in double_scalars
  J += add_term

[[0.001, 0.001, 0.001, 0.001, 0.001, 0.004216965034285823, 0.004216965034285823, 0.004216965034285823, 0.004216965034285823, 0.004216965034285823, 0.01778279410038923, 0.01778279410038923, 0.01778279410038923, 0.01778279410038923, 0.01778279410038923, 0.07498942093324558, 0.07498942093324558, 0.07498942093324558, 0.07498942093324558, 0.07498942093324558, 0.31622776601683794, 0.31622776601683794, 0.31622776601683794, 0.31622776601683794, 0.31622776601683794], [0.01, 0.03162277660168379, 0.1, 0.31622776601683794, 1.0, 0.01, 0.03162277660168379, 0.1, 0.31622776601683794, 1.0, 0.01, 0.03162277660168379, 0.1, 0.31622776601683794, 1.0, 0.01, 0.03162277660168379, 0.1, 0.31622776601683794, 1.0, 0.01, 0.03162277660168379, 0.1, 0.31622776601683794, 1.0], [-99.36285444769442, -35.03960047317326, -16.033384364607848, 17.921195377554632, -13.14041139238594, nan, nan, -46.87495047510146, -13.244783083664675, 88.44277548471658, nan, nan, -258.69912597755996, nan, -37.20823060657465, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]]

In [79]:
def read_data(data):
    cwd=os.getcwd()
    path=os.path.join(cwd,'assign_5', data)
    df=pd.read_csv(path,delimiter=',',header=None,na_values='?')
    return df

def train_test(data):
    trn,tst = train_test_split(data, test_size = 0.3,shuffle=True)
    return trn,tst

def min_max_norm(data,data_min,data_max):
    for column in data.columns:
        data[column] = (data[column] - data_min[column])/ (data_max[column]-data_min[column])    
    return data

def sigmoid(z):
    return 1/(1+np.exp(-z))

def logistic_reg(x,y,alpha,lam):
    m,n=x.shape[0],x.shape[1]
    w=np.zeros(n)
    w0,t=0,0
    err,itr,Jw,jw=100,0,[],0
    while err>0.01 and itr<100:
        for i in range(0,m):
            z=sigmoid(np.dot(w,x.iloc[i])+w0)
            t=z-y.iloc[i]
            w0=w0-alpha*t
            w_new=w-alpha*(np.dot(t,x.iloc[i])+lam*w)
            err=LA.norm(w_new-w)
            w=w_new
            jw+=(y.iloc[i]*np.log(z)+(1-y.iloc[i])*np.log(1-z))
        Jw.append(-jw+0.5*lam*pow(LA.norm(w),2))
        itr+=1
    return w0,w

def predict(data,w,w0):
    m,n=data.shape[0],data.shape[1]
    Fx,wt_x=[],[]
    for i in range(0,m):
        s1=np.dot(w,data.iloc[i]+w0)
        wt_x.append(s1)
        fx=1/(1+np.exp(-s1))
        Fx.append(fx)
    sigmoid_fn=pd.DataFrame({'wt_x': wt_x, 'f(x)': Fx})
    return sigmoid_fn

def metrics(y_tst,y_p):
    d = pd.concat([y_tst.reset_index(drop=True), y_p.reset_index(drop=True)],axis=1,ignore_index=True)
    tp=y_tst.value_counts()[1]
    tn=y_tst.value_counts()[-1]
    fp=len(d[(d[0]==-1) & (d[1]==1)])
    fn=len(d[(d[0]==1) & (d[1]==-1)])
    accuracy =(tp+tn)/(tp+tn+fp+fn)
    sensitivity=tp/(tp+fn)
    specificity=tn/(tn+fp)
    precision=tp/(tp+fp)
    fmeasure=2*(precision*sensitivity)/(precision+sensitivity)
    return tp,tn,fp,fn,accuracy,sensitivity,specificity,precision,fmeasure

# Reading the data
df=read_data('data2.csv')
# print(df.head())

X=df.iloc[:,:-1]
y=df.iloc[:,-1]
alpha,lam=0.01,0

In [80]:
# Splitting testing data into X and Y
X_trn,X_tst,y_trn,y_tst=train_test_split(X,y)

# Normalising the data using min_max method
data_min,data_max=X_trn.min(),X_trn.max()
X_trn=min_max_norm(X_trn.copy(),data_min,data_max)
X_tst=min_max_norm(X_tst.copy(),data_min,data_max)

N,n=X_tst.shape[0], X_tst.shape[1]
w0,w=logistic_reg(X_trn,y_trn,alpha,lam)

# Predicting for the test data
Fx=predict(X_tst,w,w0)
y_p=pd.DataFrame(np.where(Fx['f(x)'] >= 0.5,1, -1))
# print(y_p,y_tst.values,sep='\n')

# Performance Parameters
met=pd.DataFrame(metrics(y_tst,y_p))
met.index=['tp','tn','fp','fn','accuracy','sensitivity','specificity','precision','fmeasure']
met.columns=['Number of']


# Plotting the hyperplane
x0,x1=np.meshgrid(X_tst[0],X_tst[1])
fig = plt.figure(figsize=(12,10))
ax = plt.axes(projection ='3d')
hyp_plane=-(w0+w[0]*x0+w[1]*x1)/w[2]
ax.scatter((X_tst[0][(y_tst==1)]), (X_tst[1][(y_tst==1)]),(X_tst[2][(y_tst==1)]),c='r',label="Positive")
ax.scatter((X_tst[0][(y_tst==-1)]), (X_tst[1][(y_tst==-1)]),(X_tst[2][(y_tst==-1)]),c='g',label="Negative")
surf=ax.plot_surface(x0,x1,hyp_plane,cmap='viridis',cstride=1,rstride=1,antialiased=False,linewidth=0)
plt.legend()

# Plotting J(W)
fig = plt.figure(figsize=(12,10))
ax = fig.add_subplot()
ax.plot()
plt.show()

print("\n The Weights obtained for regularised logistic regression is", w0,w)
print("\nThe performance metrics are \n\n",met)

 The Weights obtained for regularised logistic regression is -7.846028377361978 [  5.23782139 -27.69522272  -3.68500698]

The performance metrics are

              Number of
tp           29.000000
tn           21.000000
fp           21.000000
fn            0.000000
accuracy      0.704225
sensitivity   1.000000
specificity   0.500000
precision     0.580000
fmeasure      0.734177

# Question 4 / program

In [84]:
def read_data(data):
    cwd=os.getcwd()
    path=os.path.join(cwd,'assign_5', data)
    df=pd.read_csv(path,delimiter=r"\s+",header=None,na_values='?')
    return df

def train_test(data):
    trn,tst = train_test_split(data, test_size = 0.3,shuffle=True)
    return trn,tst

def min_max_norm(data,data_min,data_max):
    for column in data.columns:
        data[column] = (data[column] - data_min[column])/ (data_max[column]-data_min[column])    
    return data

def add_bias(data):
    data.insert(0,0,1,allow_duplicates=True)
    data.columns = pd.RangeIndex(len(data.columns))
    return data

In [85]:
# Reading the data
df=read_data('auto-mpg.data')
N,n=df.shape[0], df.shape[1]
df.drop(columns=n-1,inplace=True,axis=1)
df[3]=df[3].replace(np.NaN,df[3].mean())
df[0],df[df.columns[-1]]=df[df.columns[-1]],df[0]

X=df.iloc[:,:-1]
y=df.iloc[:,-1]
lam=0.5

# Splitting testing data into X and Y
X_trn,X_tst,y_trn,y_tst=train_test_split(X,y)

# Normalising the data using min_max method
data_min,data_max=X_trn.min(),X_trn.max()
X_trn=min_max_norm(X_trn.copy(),data_min,data_max)
X_tst=min_max_norm(X_tst.copy(),data_min,data_max)
# print(X_trn)

# Adding bias to the data
X_trn=add_bias(X_trn)
X_tst=add_bias(X_tst)
N,n=X_trn.shape[0], X_trn.shape[1]

# Training using ridge regression
t0=np.identity(n-1)
t0=np.insert(t0,0,0,axis=1)
t0=np.insert(t0,0,0,axis=0)
t1=np.dot(X_trn.T,X_trn) + lam*t0
t3=np.dot(X_trn.T,y_trn)
Wr=np.dot(LA.inv(t1),t3)
print("\n The parameter obtained using ridge regression with {} as lambda is\n".format(lam), Wr)

# Evaluating the performance of the model using mean-square error  
y_p=np.dot(X_tst,Wr)
sqr_err=(y_tst-y_p)**2
mse=1/(len(y_tst)) * np.sum(sqr_err)
print("\n The mean sqaure error for the model is \n", mse)

# Training using linear regression
pinv = np.linalg.pinv(X_trn)
Wl = pinv.dot(y_trn)
print ("\nThe parameter obtained using linear regression method is \n", Wl)

# Evaluating the performance of the model using mean-square error  
y_p=np.dot(X_tst,Wl)
sqr_err=(y_tst-y_p)**2
mse=1/(len(y_tst)) * np.sum(sqr_err)
print("\n The mean sqaure error for the model is \n", mse)

 The parameter obtained using ridge regression with 0.5 as lambda is
 [ 26.96334189   2.47186709  -1.17937437  -0.07035036  -3.84420055
 -16.5768506   -0.71425688   8.54509404]

 The mean sqaure error for the model is
 10.31030027302312

The parameter obtained using linear regression method is
 [ 26.65275705   2.51522045  -0.95387685   3.31879107  -3.10045765
 -21.0088531    0.12933027   8.86342429]

 The mean sqaure error for the model is
 9.66153687416941

# Question 9 / program

In [86]:
def read_data(data):
    cwd=os.getcwd()
    path=os.path.join(cwd,'assign_5', data)
    df=pd.read_csv(path,delimiter=',',header=None,na_values='?')
    return df

In [87]:
def train_test(data):
    trn,tst = train_test_split(data, test_size = 0.3,shuffle=True)
    return trn,tst

In [88]:
def min_max_norm(data,data_min,data_max):
    for column in data.columns:
        data[column] = (data[column] - data_min[column])/ (data_max[column]-data_min[column])    
    return data

In [89]:
def add_bias(data):
    data.insert(0,0,1,allow_duplicates=True)
    data.columns = pd.RangeIndex(len(data.columns))
    return data

In [90]:
def poly_fit(Data,order):
    X=Data.copy()
    for i in range(2,order+1):
        X[i]=X[i-1]*X[1]
    return X

In [91]:
def poly_reg(X,Y):
    pinv = np.linalg.pinv(X)
    W= pinv.dot(Y)
    return W

In [92]:
# Reading the data
df=read_data('data6.csv')
X=df.iloc[:,:-1]
y=df.iloc[:,-1]

# Splitting testing data into X and Y
X_trn,X_tst,y_trn,y_tst=train_test_split(X,y)

# Normalising the data using min_max method
data_min,data_max=X_trn.min(),X_trn.max()
X_trn=min_max_norm(X_trn.copy(),data_min,data_max)
X_tst=min_max_norm(X_tst.copy(),data_min,data_max)


# Adding bias to the data
X_trn=add_bias(X_trn)
X_tst=add_bias(X_tst)
N,n=X_trn.shape[0], X_trn.shape[1]
# print(X_trn,y_trn)

# Training using 5th,7th and 9th order Polynomial regression
X5_trn=poly_fit(X_trn,5)
W5=poly_reg(X5_trn,y_trn)


X7_trn=poly_fit(X_trn,7)
W7=poly_reg(X7_trn,y_trn)

X8_trn=poly_fit(X_trn,8)
W8=poly_reg(X8_trn,y_trn)

# Testing
X5_tst=poly_fit(X_tst,5)
y_p5=np.dot(X5_tst,W5)

X7_tst=poly_fit(X_tst,7)
y_p7=np.dot(X7_tst,W7)

X8_tst=poly_fit(X_tst,8)
y_p8=np.dot(X8_tst,W8)

# plotting the points
plt.figure()
plt.plot(X_tst[1],y_tst,'ro',label='Testing points')

# 5th Degree
xs, ys = zip(*sorted(zip(X_tst[1], y_p5)))
plt.plot(xs,ys,'g', label='5th degree Fitted')

# 7th Degree
xs, ys = zip(*sorted(zip(X_tst[1], y_p7)))
plt.plot(xs,ys,'p', label='7th degree Fitted')

# 8th Degree
xs, ys = zip(*sorted(zip(X_tst[1], y_p8)))
plt.plot(xs,ys,'b', label='8th degree Fitted')
plt.legend()
plt.show()

# Question 10 / program

# Analyze Data7 using KNN

In [93]:
def read_data(data):
    cwd=os.getcwd()
    path=os.path.join(cwd,'assign_5', data)
    df=pd.read_csv(path,delimiter=',',header=None,na_values='?')
    return df

In [94]:
def train_test(data):
    trn,tst = train_test_split(data, test_size = 0.3,shuffle=True)
    return trn,tst

In [95]:
def min_max_norm(data,data_min,data_max):
    for column in data.columns:
        data[column] = (data[column] - data_min[column])/ (data_max[column]-data_min[column])    
    return data

In [96]:
def knn_classifier(X_trn,X_tst,k,y_trn):
    ind=X_trn.index
    y_p=[]
    for i in X_tst.values:
        dist=[]
        for j in X_trn.values:
            d=LA.norm(i-j)
            dist.append(d)
        df=pd.Series(dist,index=ind)
        df.sort_values(inplace=True)
        p=y_trn[df.index[:k]].mode()
        y_p.append(int(p))
    return y_p

In [97]:
def metrics(y_tst,y_p):
    d = pd.concat([y_tst.reset_index(drop=True), y_p.reset_index(drop=True)],axis=1,ignore_index=True)
    tp=y_tst.value_counts()[1]
    tn=y_tst.value_counts()[0]
    fp=len(d[(d[0]==1) & (d[1]==0)])
    fn=len(d[(d[0]==0) & (d[1]==1)])
    accuracy =(tp+tn)/(tp+tn+fp+fn)
    sensitivity=tp/(tp+fn)
    specificity=tn/(tn+fp)
    precision=tp/(tp+fp)
    fmeasure=2*(precision*sensitivity)/(precision+sensitivity)
    return tp,tn,fp,fn,accuracy,sensitivity,specificity,precision,fmeasure

In [98]:
# Reading the data
df=read_data('data7.csv')
X=df.iloc[:,:-1]
y=df.iloc[:,-1]

# Splitting testing data into X and Y
X_trn,X_tst,y_trn,y_tst=train_test_split(X,y)

# Normalising the data using min_max method
data_min,data_max=X_trn.min(),X_trn.max()
X_trn=min_max_norm(X_trn.copy(),data_min,data_max)
X_tst=min_max_norm(X_tst.copy(),data_min,data_max)

k=3

y_p=knn_classifier(X_trn,X_tst,k,y_trn)
# match=np.equal(y_p,y_tst).sum()
# Acc=match/X_tst.shape[0]

# Performance Parameters
met=pd.DataFrame(metrics(y_tst,pd.DataFrame(y_p)))
met.index=['tp','tn','fp','fn','accuracy','sensitivity','specificity','precision','fmeasure']
met.columns=['Number of']
print("\nThe performance metrics are \n\n",met)

# ROC Curve
plt.figure(2,figsize=(8,5))
plt.subplot()
fpr, tpr, threshold = roc_curve(y_tst, y_p)
plt.plot(fpr,tpr)
plt.show()

The performance metrics are

              Number of
tp           44.000000
tn           56.000000
fp            1.000000
fn            0.000000
accuracy      0.990099
sensitivity   1.000000
specificity   0.982456
precision     0.977778
fmeasure      0.988764

# Question 11

#  KNN on Breast Cancer Wisconsin (Diagnostic) Data Set

In [105]:
def read_data(data):
    cwd=os.getcwd()
    path=os.path.join(cwd,'assign_5', data)
    df=pd.read_csv(path,delimiter=',',header=None,na_values='?')
    return df

In [106]:
def train_test(data):
    trn,tst = train_test_split(data, test_size = 0.3,shuffle=True)
    return trn,tst

In [107]:
def min_max_norm(data,data_min,data_max):
    for column in data.columns:
        data[column] = (data[column] - data_min[column])/ (data_max[column]-data_min[column])    
    return data

In [108]:
def knn_classifier(X_trn,X_tst,k,y_trn):
    ind=X_trn.index
    y_p=[]
    for i in X_tst.values:
        dist=[]
        for j in X_trn.values:
            d=LA.norm(i-j)
            dist.append(d)
        df=pd.Series(dist,index=ind)
        df.sort_values(inplace=True)
        p=y_trn[df.index[:k]].mode()
        y_p.append(int(p))
    return y_p

In [110]:
# Reading the data
df=read_data('breast-cancer-wisconsin.data')
df.drop(columns=0,inplace=True) #Dropping the ID column
df.dropna(inplace=True) #Dropping rows with Nan values

# Splitting to X and y parts 
X=df.iloc[:,:-1]
y=df.iloc[:,-1]

#K-fold cross validation
folds = 5
kf = KFold(n_splits=folds, random_state=None) 
Acc=[] 
for train_index , test_index in kf.split(X):
    X_trn , X_tst = X.iloc[train_index,:],X.iloc[test_index,:]
    y_trn , y_tst = y.iloc[train_index] , y.iloc[test_index]


    # Normalising the data using min_max method
    data_min,data_max=X_trn.min(),X_trn.max()
    X_trn=min_max_norm(X_trn.copy(),data_min,data_max)
    X_tst=min_max_norm(X_tst.copy(),data_min,data_max)

    k=3

    y_p=knn_classifier(X_trn,X_tst,k,y_trn)
    match=np.equal(y_p,y_tst).sum()
    Acc.append(match*100/X_tst.shape[0])

# Result for k-fold Method
print("\nAccuracy of folds is",Acc)

# Hold-out method
k=[3,5,7,11]
Acc=[] 
for k in k:
    y_p=knn_classifier(X_trn,X_tst,k,y_trn)
    match=np.equal(y_p,y_tst).sum()
    Acc.append(match*100/X_tst.shape[0])
    
# Result for Holdout Method
print("\nAccuracy for different k's is",Acc)

Accuracy of folds is [93.43065693430657, 96.35036496350365, 96.35036496350365, 99.26470588235294, 98.52941176470588]

Accuracy for different k's is [98.52941176470588, 99.26470588235294, 100.0, 100.0]